using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ftms.domain
{
    public class File
    {
        public int FileId { get; set; }
        public string? FileNumber { get; set; }
        public bool AutoGenerated { get; set; }
        public string? FileAlias { get; set; }
        public int FileTypeId { get; set; }
        public int? OwnerId { get; set; }
        public string? FileStatusCode { get; set; }
        public string? PropertyNo { get; set; }
        public decimal? PropertySize { get; set; }
        public string? LocationCode { get; set; }
        public string? LanduseCode { get; set; }
        public string? LandpurposeCode { get; set; }
        public DateTime Recordation { get; set; }
        public bool Active { get; set; }
        public int? LeaseyearCode { get; set; }
        public bool RofoExists { get; set; }
        public bool CofoExists { get; set; }
        public int ModifiedBy { get; set; }
        public string? AllocationStatus { get; set; }
        public string? TransactionStatus { get; set; }
        public int? OtherClaimantsCode { get; set; }
        public int? FileNumberOnly { get; set; }
    }
}
